### ISSUE TITLE
Got an error while running the example code 

### ISSUE THREAD

**Issue by orklann** [LouisT/GistDB#2]
Got an error while running the example code in README.md

```
Init called: false
There was an error! (Error: Could not parse content.)
```

Anyone can help?

**Comment by LouisT** [comment]
Hello, I haven't worked on this project in many years. I wouldn't doubt that the entire gist API has changed by now. If I were to fix it, it'd most likely be better for a full rewrite as this code is so old. If you're still wanting to use it, perhaps I could look into this.
